### ISSUE TITLE
get_re_var() function?

### ISSUE THREAD

**Issue by jrosen48** [strengejacke/sjmisc#112]
Hi, is the `get_re_var()` function available in another package (or is `re_var()` available?)? I checked the `news.md` file and didn't see this was deprecated; but believe it was in an older version (e.g., [1.8](https://www.rdocumentation.org/packages/sjmisc/versions/1.8/topics/get_re_var)).

**Comment by strengejacke** [comment]
It _was_ in sjstats, but is now reimplemented in [`insight::get_variance()`](https://easystats.github.io/insight/reference/get_variance.html).

**Comment by strengejacke** [comment]
I close this now. Feel free to re-open if you have further questions.
