### ISSUE TITLE
Arguement "show" in descr

### ISSUE THREAD

**Issue by ptogias** [strengejacke/sjmisc#115]
**Question and context**
It seems like I can't pass the "show" argument in the descr function.. Any ideas how I can select specific statistics?

This is the error I get every time using show = "short"
`Error: Unknown column `short` `

**Comment by strengejacke** [comment]
Have you installed the latest pkg version from GitHub?

**Comment by ptogias** [comment]
I updated the package from GitHub and the issue seems to be solved. I think there's one more issue though when using the group_by function from dplyr and viewing the output from a browser (out = "browser")

`  efc %>%
    group_by(e16sex) %>%
    select(e16sex, e42dep, e15relat, c172code) %>%
    descr(out = "browser")
`
the error that pops up is

`Error: Result 1 must be a single string, not a character vector of length 0`

Backtrace shows 

`class:   `purrr_error_bad_element_vector`
backtrace:
 1. (function (x, ...) ...
 6. purrr:::stop_bad_element_vector(...)
 7. purrr:::stop_bad_vector(...)
 8. purrr:::stop_bad_type(...)
`

**Comment by strengejacke** [comment]
thanks, should be fixed now!
