### ISSUE TITLE
frq behaves weirdly - only works with data["col"], but not data$col

### ISSUE THREAD

**Issue by phildias** [strengejacke/sjmisc#116]
For some reason, when I use the `frq` command with my dataset, it only actually outputs the frequencies when I access the specific column of interest using the square bracket operator (`data["col"]`), but not when I use the dollar sign operator (`data$col`).

It might be a problem associated with my specific dataset, but I'm not completely sure what's triggering it. Either way, [here](https://www.dropbox.com/s/x5jdudr9ueg16wm/subdata.RData?dl=0) is the data I'm currently using. 

For reproducibility, here is the code:
```
load(file = "subdata.RData")
sjmisc::frq(x = subdata["ExtHTMLRef"], out="viewer")
sjmisc::frq(x = subdata$ExtHTMLRef, out="viewer")
```
The first frq command works, but the second one just outputs "NULL" in the R console.

If I refactor the column (i.e. running `subdata$ExtHTMLRef = factor(subdata$ExtHTMLRef)`) , both versions work fine.

I also tried investigating if it's something specific to "character"-type columns, but that doesn't seem to be the case. 

Any kind of info about this odd behavior would be very appreciated.

Thanks!!!

**Comment by iago-pssjd** [comment]
It is, indeed, an issue specific for character-type columns, since in this case, when the function `is_empty` checks if the evaluated vector is empty, it only takes into consideration the first element. Since in this case is `""`, it is considered to be empty, so `frq` returns NULL.

I can make on next days a small PR solving this issue.

**Comment by strengejacke** [comment]
Can you provide the data by directly attaching a zip-file here? my company forbids access from DropBox.

**Comment by phildias** [comment]
Oh, great! It sounds like an easy fix then. Here's the file! Thanks!
[subdata.zip](https://github.com/strengejacke/sjmisc/files/3579796/subdata.zip)

**Comment by strengejacke** [comment]
Thanks for the fix!
