### ISSUE TITLE
edit output plot from merge_imputations "dens"

### ISSUE THREAD

**Issue by quia27** [strengejacke/sjmisc#125]
I'd like to edit the output plot from merge_imputations(.,summary = "dens")--e.g., change title, legend position, etc... I tried to treat the output as a ggplot but it did not work. It looks like a lattice::xyplot. If so, is it possible to change plot parameters from the output? Thanks

**Comment by strengejacke** [comment]
I slightly revised the function, so it also returns the plot as `$plot` element of the list (which is indeed a ggplot-object)
