### ISSUE TITLE
Important bug in Rec

### ISSUE THREAD

**Issue by andresimi** [strengejacke/sjmisc#136]
I think this is a bug.

```
library(sjmisc)

> rec(4, rec = "min:5=low; 6:10=high")
[1] "low"
> rec(4, rec = "min:5=low; 6:max=high")
[1] "high"
```

**Comment by andresimi** [comment]
Hi, I noticed that samething has changed but I am not understanding the rec behavior. Is something wrong with my code?

`
> library(sjmisc)
> rec(4, rec = "min:5=low; 6:10=high")
[1] "low"
> rec(4, rec = "min:5=low; 6:max=high")
Erro: ?Syntax error in recode range from 6 to 4.
> rec(4, rec = "min:5=low; max:6=high")
[1] "high"`

**Comment by strengejacke** [comment]
Your highest number is 4, but you request a range from 6 to highest number. This is not possible, since the 6 is larger than the highest number, 4.
