### ISSUE TITLE
FR: allow more printing formatting for frq

### ISSUE THREAD

**Issue by iago-pssjd** [strengejacke/sjmisc#145]
Since `print.sjmisc_frq` uses `insight::export_table`, it would be nice to have the `format` option for `frq`, to allow printing markdown or html.

Thank you!

**Comment by strengejacke** [comment]
``` r
library(sjmisc)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

data(efc)
frq(efc$e42dep)
#> elder's dependency (x) <numeric> 
#> # total N=908 valid N=901 mean=2.94 sd=0.94
#> 
#> Value |                Label |   N | Raw % | Valid % | Cum. %
#> -------------------------------------------------------------
#>     1 |          independent |  66 |  7.27 |    7.33 |   7.33
#>     2 |   slightly dependent | 225 | 24.78 |   24.97 |  32.30
#>     3 | moderately dependent | 306 | 33.70 |   33.96 |  66.26
#>     4 |   severely dependent | 304 | 33.48 |   33.74 | 100.00
#>  <NA> |                 <NA> |   7 |  0.77 |    <NA> |   <NA>

frq(efc$e42dep) |> print_md()
```

| Value |                Label |   N | Raw % | Valid % | Cum. % |
|------:|---------------------:|----:|------:|--------:|-------:|
|     1 |          independent |  66 |  7.27 |    7.33 |   7.33 |
|     2 |   slightly dependent | 225 | 24.78 |   24.97 |  32.30 |
|     3 | moderately dependent | 306 | 33.70 |   33.96 |  66.26 |
|     4 |   severely dependent | 304 | 33.48 |   33.74 | 100.00 |
|  <NA> |                 <NA> |   7 |  0.77 |    <NA> |   <NA> |

elder’s dependency (x) <numeric>

total N=908 valid N=901 mean=2.94 sd=0.94

``` r
frq(efc$e42dep) |> print_html()
```
<table class="gt_table">
  <thead class="gt_header">
    <tr>
      <th colspan="6" class="gt_heading gt_title gt_font_normal gt_bottom_border" style>elder's dependency (x)</th>
    </tr>
    
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">Value</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">Label</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">N</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">Raw %</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">Valid %</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">Cum. %</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">1</td>
<td class="gt_row gt_center">independent</td>
<td class="gt_row gt_center">66</td>
<td class="gt_row gt_center">7.27</td>
<td class="gt_row gt_center">7.33</td>
<td class="gt_row gt_center">7.33</td></tr>
    <tr><td class="gt_row gt_left">2</td>
<td class="gt_row gt_center">slightly dependent</td>
<td class="gt_row gt_center">225</td>
<td class="gt_row gt_center">24.78</td>
<td class="gt_row gt_center">24.97</td>
<td class="gt_row gt_center">32.30</td></tr>
    <tr><td class="gt_row gt_left">3</td>
<td class="gt_row gt_center">moderately dependent</td>
<td class="gt_row gt_center">306</td>
<td class="gt_row gt_center">33.70</td>
<td class="gt_row gt_center">33.96</td>
<td class="gt_row gt_center">66.26</td></tr>
    <tr><td class="gt_row gt_left">4</td>
<td class="gt_row gt_center">severely dependent</td>
<td class="gt_row gt_center">304</td>
<td class="gt_row gt_center">33.48</td>
<td class="gt_row gt_center">33.74</td>
<td class="gt_row gt_center">100.00</td></tr>
    <tr><td class="gt_row gt_left">&lt;NA&gt;</td>
<td class="gt_row gt_center">&lt;NA&gt;</td>
<td class="gt_row gt_center">7</td>
<td class="gt_row gt_center">0.77</td>
<td class="gt_row gt_center">&lt;NA&gt;</td>
<td class="gt_row gt_center">&lt;NA&gt;</td></tr>
  </tbody>
  <tfoot class="gt_sourcenotes"></tfoot>
  
</table>

``` r
efc |> 
  group_by(e16sex, c172code) |> 
  frq(e42dep)
#> elder's dependency (e42dep) <numeric> 
#> # grouped by: male, low level of education
#> # total N=80 valid N=80 mean=3.06 sd=0.92
#> 
#> Value |                Label |  N | Raw % | Valid % | Cum. %
#> ------------------------------------------------------------
#>     1 |          independent |  5 |  6.25 |    6.25 |   6.25
#>     2 |   slightly dependent | 16 | 20.00 |   20.00 |  26.25
#>     3 | moderately dependent | 28 | 35.00 |   35.00 |  61.25
#>     4 |   severely dependent | 31 | 38.75 |   38.75 | 100.00
#>  <NA> |                 <NA> |  0 |  0.00 |    <NA> |   <NA>
#> 
#> elder's dependency (e42dep) <numeric> 
#> # grouped by: male, intermediate level of education
#> # total N=156 valid N=156 mean=2.83 sd=0.94
#> 
#> Value |                Label |  N | Raw % | Valid % | Cum. %
#> ------------------------------------------------------------
#>     1 |          independent | 15 |  9.62 |    9.62 |   9.62
#>     2 |   slightly dependent | 39 | 25.00 |   25.00 |  34.62
#>     3 | moderately dependent | 59 | 37.82 |   37.82 |  72.44
#>     4 |   severely dependent | 43 | 27.56 |   27.56 | 100.00
#>  <NA> |                 <NA> |  0 |  0.00 |    <NA> |   <NA>
#> 
#> elder's dependency (e42dep) <numeric> 
#> # grouped by: male, high level of education
#> # total N=43 valid N=43 mean=2.91 sd=0.81
#> 
#> Value |                Label |  N | Raw % | Valid % | Cum. %
#> ------------------------------------------------------------
#>     1 |          independent |  1 |  2.33 |    2.33 |   2.33
#>     2 |   slightly dependent | 13 | 30.23 |   30.23 |  32.56
#>     3 | moderately dependent | 18 | 41.86 |   41.86 |  74.42
#>     4 |   severely dependent | 11 | 25.58 |   25.58 | 100.00
#>  <NA> |                 <NA> |  0 |  0.00 |    <NA> |   <NA>
#> 
#> elder's dependency (e42dep) <numeric> 
#> # grouped by: female, low level of education
#> # total N=99 valid N=99 mean=2.95 sd=0.94
#> 
#> Value |                Label |  N | Raw % | Valid % | Cum. %
#> ------------------------------------------------------------
#>     1 |          independent |  7 |  7.07 |    7.07 |   7.07
#>     2 |   slightly dependent | 25 | 25.25 |   25.25 |  32.32
#>     3 | moderately dependent | 33 | 33.33 |   33.33 |  65.66
#>     4 |   severely dependent | 34 | 34.34 |   34.34 | 100.00
#>  <NA> |                 <NA> |  0 |  0.00 |    <NA> |   <NA>
#> 
#> elder's dependency (e42dep) <numeric> 
#> # grouped by: female, intermediate level of education
#> # total N=350 valid N=350 mean=2.90 sd=0.98
#> 
#> Value |                Label |   N | Raw % | Valid % | Cum. %
#> -------------------------------------------------------------
#>     1 |          independent |  30 |  8.57 |    8.57 |   8.57
#>     2 |   slightly dependent |  96 | 27.43 |   27.43 |  36.00
#>     3 | moderately dependent | 104 | 29.71 |   29.71 |  65.71
#>     4 |   severely dependent | 120 | 34.29 |   34.29 | 100.00
#>  <NA> |                 <NA> |   0 |  0.00 |    <NA> |   <NA>
#> 
#> elder's dependency (e42dep) <numeric> 
#> # grouped by: female, high level of education
#> # total N=113 valid N=113 mean=3.04 sd=0.85
#> 
#> Value |                Label |  N | Raw % | Valid % | Cum. %
#> ------------------------------------------------------------
#>     1 |          independent |  4 |  3.54 |    3.54 |   3.54
#>     2 |   slightly dependent | 26 | 23.01 |   23.01 |  26.55
#>     3 | moderately dependent | 44 | 38.94 |   38.94 |  65.49
#>     4 |   severely dependent | 39 | 34.51 |   34.51 | 100.00
#>  <NA> |                 <NA> |  0 |  0.00 |    <NA> |   <NA>


efc |> 
  group_by(e16sex, c172code) |> 
  frq(e42dep) |> 
  print_md()
```

| Value |                Label |   N | Raw % | Valid % | Cum. % |
|------:|---------------------:|----:|------:|--------:|-------:|
|     1 |          independent |   5 |  6.25 |    6.25 |   6.25 |
|     2 |   slightly dependent |  16 | 20.00 |   20.00 |  26.25 |
|     3 | moderately dependent |  28 | 35.00 |   35.00 |  61.25 |
|     4 |   severely dependent |  31 | 38.75 |   38.75 | 100.00 |
|  <NA> |                 <NA> |   0 |  0.00 |    <NA> |   <NA> |

elder’s dependency (e42dep) <numeric> grouped by: male, low level of education

total N=80 valid N=80 mean=3.06 sd=0.92

| Value |                Label | N   | Raw % | Valid % | Cum. % |
|------:|---------------------:|:----|------:|--------:|-------:|
|     1 |          independent | 15  |  9.62 |    9.62 |   9.62 |
|     2 |   slightly dependent | 39  | 25.00 |   25.00 |  34.62 |
|     3 | moderately dependent | 59  | 37.82 |   37.82 |  72.44 |
|     4 |   severely dependent | 43  | 27.56 |   27.56 | 100.00 |
|  <NA> |                 <NA> | 0   |  0.00 |    <NA> |   <NA> |

elder’s dependency (e42dep) <numeric> grouped by: male, intermediate level of education

total N=156 valid N=156 mean=2.83 sd=0.94

| Value |                Label |   N | Raw % | Valid % | Cum. % |
|------:|---------------------:|----:|------:|--------:|-------:|
|     1 |          independent |   1 |  2.33 |    2.33 |   2.33 |
|     2 |   slightly dependent |  13 | 30.23 |   30.23 |  32.56 |
|     3 | moderately dependent |  18 | 41.86 |   41.86 |  74.42 |
|     4 |   severely dependent |  11 | 25.58 |   25.58 | 100.00 |
|  <NA> |                 <NA> |   0 |  0.00 |    <NA> |   <NA> |

elder’s dependency (e42dep) <numeric> grouped by: male, high level of education

total N=43 valid N=43 mean=2.91 sd=0.81

| Value |                Label |   N | Raw % | Valid % | Cum. % |
|------:|---------------------:|----:|------:|--------:|-------:|
|     1 |          independent |   7 |  7.07 |    7.07 |   7.07 |
|     2 |   slightly dependent |  25 | 25.25 |   25.25 |  32.32 |
|     3 | moderately dependent |  33 | 33.33 |   33.33 |  65.66 |
|     4 |   severely dependent |  34 | 34.34 |   34.34 | 100.00 |
|  <NA> |                 <NA> |   0 |  0.00 |    <NA> |   <NA> |

elder’s dependency (e42dep) <numeric> grouped by: female, low level of education

total N=99 valid N=99 mean=2.95 sd=0.94

| Value |                Label |   N | Raw % | Valid % | Cum. % |
|------:|---------------------:|----:|------:|--------:|-------:|
|     1 |          independent |  30 |  8.57 |    8.57 |   8.57 |
|     2 |   slightly dependent |  96 | 27.43 |   27.43 |  36.00 |
|     3 | moderately dependent | 104 | 29.71 |   29.71 |  65.71 |
|     4 |   severely dependent | 120 | 34.29 |   34.29 | 100.00 |
|  <NA> |                 <NA> |   0 |  0.00 |    <NA> |   <NA> |

elder’s dependency (e42dep) <numeric> grouped by: female, intermediate level of education

total N=350 valid N=350 mean=2.90 sd=0.98

| Value |                Label |   N | Raw % | Valid % | Cum. % |
|------:|---------------------:|----:|------:|--------:|-------:|
|     1 |          independent |   4 |  3.54 |    3.54 |   3.54 |
|     2 |   slightly dependent |  26 | 23.01 |   23.01 |  26.55 |
|     3 | moderately dependent |  44 | 38.94 |   38.94 |  65.49 |
|     4 |   severely dependent |  39 | 34.51 |   34.51 | 100.00 |
|  <NA> |                 <NA> |   0 |  0.00 |    <NA> |   <NA> |

elder’s dependency (e42dep) <numeric> grouped by: female, high level of education

total N=113 valid N=113 mean=3.04 sd=0.85

``` r
efc |> 
  group_by(e16sex, c172code) |> 
  frq(e42dep) |> 
  print_html()
```
<table class="gt_table">
  <thead class="gt_header">
    <tr>
      <th colspan="6" class="gt_heading gt_title gt_font_normal gt_bottom_border" style>elder's dependency (e42dep)</th>
    </tr>
    
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">Value</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">Label</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">N</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">Raw %</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">Valid %</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">Cum. %</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr class="gt_group_heading_row">
      <td colspan="6" class="gt_group_heading">elder's dependency (e42dep), grouped by: male, low level of education</td>
    </tr>
    <tr><td class="gt_row gt_left">1</td>
<td class="gt_row gt_center">independent</td>
<td class="gt_row gt_center">5</td>
<td class="gt_row gt_center">6.25</td>
<td class="gt_row gt_center">6.25</td>
<td class="gt_row gt_center">6.25</td></tr>
    <tr><td class="gt_row gt_left">2</td>
<td class="gt_row gt_center">slightly dependent</td>
<td class="gt_row gt_center">16</td>
<td class="gt_row gt_center">20.00</td>
<td class="gt_row gt_center">20.00</td>
<td class="gt_row gt_center">26.25</td></tr>
    <tr><td class="gt_row gt_left">3</td>
<td class="gt_row gt_center">moderately dependent</td>
<td class="gt_row gt_center">28</td>
<td class="gt_row gt_center">35.00</td>
<td class="gt_row gt_center">35.00</td>
<td class="gt_row gt_center">61.25</td></tr>
    <tr><td class="gt_row gt_left">4</td>
<td class="gt_row gt_center">severely dependent</td>
<td class="gt_row gt_center">31</td>
<td class="gt_row gt_center">38.75</td>
<td class="gt_row gt_center">38.75</td>
<td class="gt_row gt_center">100.00</td></tr>
    <tr><td class="gt_row gt_left">&lt;NA&gt;</td>
<td class="gt_row gt_center">&lt;NA&gt;</td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">&lt;NA&gt;</td>
<td class="gt_row gt_center">&lt;NA&gt;</td></tr>
    <tr class="gt_group_heading_row">
      <td colspan="6" class="gt_group_heading">elder's dependency (e42dep), grouped by: male, intermediate level of education</td>
    </tr>
    <tr><td class="gt_row gt_left">1</td>
<td class="gt_row gt_center">independent</td>
<td class="gt_row gt_center">15</td>
<td class="gt_row gt_center">9.62</td>
<td class="gt_row gt_center">9.62</td>
<td class="gt_row gt_center">9.62</td></tr>
    <tr><td class="gt_row gt_left">2</td>
<td class="gt_row gt_center">slightly dependent</td>
<td class="gt_row gt_center">39</td>
<td class="gt_row gt_center">25.00</td>
<td class="gt_row gt_center">25.00</td>
<td class="gt_row gt_center">34.62</td></tr>
    <tr><td class="gt_row gt_left">3</td>
<td class="gt_row gt_center">moderately dependent</td>
<td class="gt_row gt_center">59</td>
<td class="gt_row gt_center">37.82</td>
<td class="gt_row gt_center">37.82</td>
<td class="gt_row gt_center">72.44</td></tr>
    <tr><td class="gt_row gt_left">4</td>
<td class="gt_row gt_center">severely dependent</td>
<td class="gt_row gt_center">43</td>
<td class="gt_row gt_center">27.56</td>
<td class="gt_row gt_center">27.56</td>
<td class="gt_row gt_center">100.00</td></tr>
    <tr><td class="gt_row gt_left">&lt;NA&gt;</td>
<td class="gt_row gt_center">&lt;NA&gt;</td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">&lt;NA&gt;</td>
<td class="gt_row gt_center">&lt;NA&gt;</td></tr>
    <tr class="gt_group_heading_row">
      <td colspan="6" class="gt_group_heading">elder's dependency (e42dep), grouped by: male, high level of education</td>
    </tr>
    <tr><td class="gt_row gt_left">1</td>
<td class="gt_row gt_center">independent</td>
<td class="gt_row gt_center">1</td>
<td class="gt_row gt_center">2.33</td>
<td class="gt_row gt_center">2.33</td>
<td class="gt_row gt_center">2.33</td></tr>
    <tr><td class="gt_row gt_left">2</td>
<td class="gt_row gt_center">slightly dependent</td>
<td class="gt_row gt_center">13</td>
<td class="gt_row gt_center">30.23</td>
<td class="gt_row gt_center">30.23</td>
<td class="gt_row gt_center">32.56</td></tr>
    <tr><td class="gt_row gt_left">3</td>
<td class="gt_row gt_center">moderately dependent</td>
<td class="gt_row gt_center">18</td>
<td class="gt_row gt_center">41.86</td>
<td class="gt_row gt_center">41.86</td>
<td class="gt_row gt_center">74.42</td></tr>
    <tr><td class="gt_row gt_left">4</td>
<td class="gt_row gt_center">severely dependent</td>
<td class="gt_row gt_center">11</td>
<td class="gt_row gt_center">25.58</td>
<td class="gt_row gt_center">25.58</td>
<td class="gt_row gt_center">100.00</td></tr>
    <tr><td class="gt_row gt_left">&lt;NA&gt;</td>
<td class="gt_row gt_center">&lt;NA&gt;</td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">&lt;NA&gt;</td>
<td class="gt_row gt_center">&lt;NA&gt;</td></tr>
    <tr class="gt_group_heading_row">
      <td colspan="6" class="gt_group_heading">elder's dependency (e42dep), grouped by: female, low level of education</td>
    </tr>
    <tr><td class="gt_row gt_left">1</td>
<td class="gt_row gt_center">independent</td>
<td class="gt_row gt_center">7</td>
<td class="gt_row gt_center">7.07</td>
<td class="gt_row gt_center">7.07</td>
<td class="gt_row gt_center">7.07</td></tr>
    <tr><td class="gt_row gt_left">2</td>
<td class="gt_row gt_center">slightly dependent</td>
<td class="gt_row gt_center">25</td>
<td class="gt_row gt_center">25.25</td>
<td class="gt_row gt_center">25.25</td>
<td class="gt_row gt_center">32.32</td></tr>
    <tr><td class="gt_row gt_left">3</td>
<td class="gt_row gt_center">moderately dependent</td>
<td class="gt_row gt_center">33</td>
<td class="gt_row gt_center">33.33</td>
<td class="gt_row gt_center">33.33</td>
<td class="gt_row gt_center">65.66</td></tr>
    <tr><td class="gt_row gt_left">4</td>
<td class="gt_row gt_center">severely dependent</td>
<td class="gt_row gt_center">34</td>
<td class="gt_row gt_center">34.34</td>
<td class="gt_row gt_center">34.34</td>
<td class="gt_row gt_center">100.00</td></tr>
    <tr><td class="gt_row gt_left">&lt;NA&gt;</td>
<td class="gt_row gt_center">&lt;NA&gt;</td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">&lt;NA&gt;</td>
<td class="gt_row gt_center">&lt;NA&gt;</td></tr>
    <tr class="gt_group_heading_row">
      <td colspan="6" class="gt_group_heading">elder's dependency (e42dep), grouped by: female, intermediate level of education</td>
    </tr>
    <tr><td class="gt_row gt_left">1</td>
<td class="gt_row gt_center">independent</td>
<td class="gt_row gt_center">30</td>
<td class="gt_row gt_center">8.57</td>
<td class="gt_row gt_center">8.57</td>
<td class="gt_row gt_center">8.57</td></tr>
    <tr><td class="gt_row gt_left">2</td>
<td class="gt_row gt_center">slightly dependent</td>
<td class="gt_row gt_center">96</td>
<td class="gt_row gt_center">27.43</td>
<td class="gt_row gt_center">27.43</td>
<td class="gt_row gt_center">36.00</td></tr>
    <tr><td class="gt_row gt_left">3</td>
<td class="gt_row gt_center">moderately dependent</td>
<td class="gt_row gt_center">104</td>
<td class="gt_row gt_center">29.71</td>
<td class="gt_row gt_center">29.71</td>
<td class="gt_row gt_center">65.71</td></tr>
    <tr><td class="gt_row gt_left">4</td>
<td class="gt_row gt_center">severely dependent</td>
<td class="gt_row gt_center">120</td>
<td class="gt_row gt_center">34.29</td>
<td class="gt_row gt_center">34.29</td>
<td class="gt_row gt_center">100.00</td></tr>
    <tr><td class="gt_row gt_left">&lt;NA&gt;</td>
<td class="gt_row gt_center">&lt;NA&gt;</td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">&lt;NA&gt;</td>
<td class="gt_row gt_center">&lt;NA&gt;</td></tr>
    <tr class="gt_group_heading_row">
      <td colspan="6" class="gt_group_heading">elder's dependency (e42dep), grouped by: female, high level of education</td>
    </tr>
    <tr><td class="gt_row gt_left">1</td>
<td class="gt_row gt_center">independent</td>
<td class="gt_row gt_center">4</td>
<td class="gt_row gt_center">3.54</td>
<td class="gt_row gt_center">3.54</td>
<td class="gt_row gt_center">3.54</td></tr>
    <tr><td class="gt_row gt_left">2</td>
<td class="gt_row gt_center">slightly dependent</td>
<td class="gt_row gt_center">26</td>
<td class="gt_row gt_center">23.01</td>
<td class="gt_row gt_center">23.01</td>
<td class="gt_row gt_center">26.55</td></tr>
    <tr><td class="gt_row gt_left">3</td>
<td class="gt_row gt_center">moderately dependent</td>
<td class="gt_row gt_center">44</td>
<td class="gt_row gt_center">38.94</td>
<td class="gt_row gt_center">38.94</td>
<td class="gt_row gt_center">65.49</td></tr>
    <tr><td class="gt_row gt_left">4</td>
<td class="gt_row gt_center">severely dependent</td>
<td class="gt_row gt_center">39</td>
<td class="gt_row gt_center">34.51</td>
<td class="gt_row gt_center">34.51</td>
<td class="gt_row gt_center">100.00</td></tr>
    <tr><td class="gt_row gt_left">&lt;NA&gt;</td>
<td class="gt_row gt_center">&lt;NA&gt;</td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">&lt;NA&gt;</td>
<td class="gt_row gt_center">&lt;NA&gt;</td></tr>
  </tbody>
  <tfoot class="gt_sourcenotes"></tfoot>
  
</table>

<sup>Created on 2021-11-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
