### ISSUE TITLE
question: row_sums for count indices?

### ISSUE THREAD

**Issue by methodds** [strengejacke/sjmisc#55]
Hi,

can the new ``row_sums()`` function somehow also be used for creating count indices? This  is possible with ``rowSums()``, e.g. like this:

```

library(sjmisc)
library(dplyr)
data(efc)

         
cop <- select(efc, contains("cop")) %>% 
  mutate(index = rowSums(.==4, na.rm=TRUE))
head(cop)


 c82cop1 c83cop2 c84cop3 c85cop4 c86cop5 c87cop6 c88cop7 c89cop8 c90cop9 index
1       3       2       2       2       1       1       2       3       3     0
2       3       3       3       3       4       1       3       2       2     1
3       2       2       1       4       1       1       1       4       3     2
4       4       1       3       1       1       1       1       2       4     2
5       3       2       1       2       2       2       1       4       4     2
6       2       2       3       3       3       2       2       1       1     0
```
A way to quickly create an count index (without ugly syntax) would be useful, especially for social scientists working with likert scales. Maybe the function could just use an additional parameter, ``count=NULL``, which, after passing a value or a vector of values, would then mimic the behavior of ``rowSums()``?

Edit: It would be even nicer if this could also be used to count rowwise missing values =).
Edit2: I just discovered ``count_na()`` but this seems to create a frequency table and not a column

**Comment by strengejacke** [comment]
Yes, `count_na()` is just for tagged NA values, to see how many "different" NA's are in a variable. I could add methods `row_count()` and `col_count()`, because counting idices isn't really a "sum" ;-)

**Comment by methodds** [comment]
Ye I guess you're right, that's not a sum.. I think it would be a very useful addition to the package :)
