### ISSUE TITLE
R crashes when using add_columns inside a pipe workflow

### ISSUE THREAD

**Issue by caayala** [strengejacke/sjmisc#56]
This code crash my R session.

```
library(tidyverse)
library(sjmisc)

iris2 <- iris %>% 
  row_sums(~contains('Sepal'), var = 'Sepal_sum') %>% 
  add_columns()
```

**Comment by strengejacke** [comment]
Thanks. You need to specify at least one more data frame with columns to add. If you don't, the `...`-argument is `NULL`, which causes the call to `dplyr::bind_cols(...)` to crash (try `dplyr::bind_cols(NULL)`).

I now added a check if `...` is given, and if not, `add_columns()` and `replace_columns()` will give an error.
