### ISSUE TITLE
output from frq()

### ISSUE THREAD

**Issue by methodds** [strengejacke/sjmisc#60]
Hi,

I'm currently using the sjverse for teaching undergraduates how to do quantitative stuff and overall it works really well thanks to your awesome work!

One of the commands we use frequently (haha) is ``frq()`` and there are two quirks in the output which confuse newcomers:

### 1)

   NA's (even if there are none in the corresponding variables) always get appended to the remaining output with a "val" of the last "val" + 1:

```
library(sjmisc)
data(efc)

frq(efc$c82cop1)
frq(efc$e17age)


# do you feel you cope well as caregiver?

 val     label frq raw.prc valid.prc cum.prc
   1     never   3    0.33      0.33    0.33
   2 sometimes  97   10.68     10.77   11.10
   3     often 591   65.09     65.59   76.69
   4    always 210   23.13     23.31  100.00
   5        NA   7    0.77        NA      NA


> frq(efc$e17age)
# elder' age

 val frq label raw.prc valid.prc cum.prc
  65  32    65    3.52      3.59    3.59
  66  24    66    2.64      2.69    6.29
  67  29    67    3.19      3.25    9.54
  68  24    68    2.64      2.69   12.23
  69  29    69    3.19      3.25   15.49
  ....
  95   7    95    0.77      0.79   98.99
  96   1    96    0.11      0.11   99.10
  97   5    97    0.55      0.56   99.66
  98   1    98    0.11      0.11   99.78
  99   1    99    0.11      0.11   99.89
 103   1   103    0.11      0.11  100.00
 104  17    NA    1.87        NA      NA
```
This led to some students misreading the frequencies and actually thinking that people with an age of 104 exist in the dataset. I think this could for instance be solved by replacing the "val" value for NA , here the number 104, with  "NA". After all, any value, no matter which one it is, doesn't really make sense for NA's here.  Related to this, a parameter for frq() would be useful where users could choose whether they want NA's to be included in the output. I'm having trouble with implementing this own my own as the function `frq()` and `frq_helper()` do not contain any comments explaining the code.

### 2)
When using weights and the input data does not contain any NA's, displaying valid.prc and cum.prc  for the last category does not work properly:

```
efc$weights <- sample(c(0,1), nrow(efc), replace = T)
efc$no_na <- rec(efc$c82cop1, rec = 'NA = 2; else = copy')

frq(efc$c82cop1, weight.by = efc$weights)
frq(efc$no_na, weight.by = efc$weights)

> frq(efc$c82cop1, weight.by = efc$weights)
# do you feel you cope well as caregiver?

 val     label frq raw.prc valid.prc cum.prc
   1     never   1    0.23      0.11    0.11
   2 sometimes  56   12.84      6.22    6.33
   3     often 278   63.76     30.85   37.18
   4    always  99   22.71     10.99   48.17
   5        NA   2    0.46        NA      NA


> 
> frq(efc$no_na, weight.by = efc$weights)
# do you feel you cope well as caregiver?

 val frq label raw.prc valid.prc cum.prc
   1   1     1    0.23      0.11    0.11
   2  58     2   13.30      6.39    6.50
   3 278     3   63.76     30.62   37.11
   4  99     4   22.71        NA      NA
```

**Comment by strengejacke** [comment]
I'm not sure, I remember, there was a reason for giving the NA-value a value-number - maybe, this is no longer necessary, quick tests did not reveal any problems. I'll commit tonight, you may check whether you encounter any issues.
