### ISSUE TITLE
Convert factor to numeric using the value labels?

### ISSUE THREAD

**Issue by dannyparsons** [strengejacke/sjmisc#61]
Is there a function in `sjmisc` to convert a factor to numeric using the value labels to determine the conversion? Kind of like the reverse of `to_label`. I thought `to_value` might do this but this uses the factor index numbers instead. 

What I'd like to be able to is:
1. start with a factor column
2. associate numeric values to it through the labels attribute
3. convert the factor to numeric using the numeric values from the labels

Example:
```
x <- c(0, 0.5, 1, 1.5)
labs <- c(0, 0.5, 1, 1.5)
names(labs) <- c("None", "Little", "Some", "Lots")
x <- set_labels(x, labels = labs)
x <- to_factor(x)
x
# [1] None   Little Some   Lots  
# attr(,"labels")
#   None Little   Some   Lots 
#    0.0    0.5    1.0    1.5 
# Levels: None Little Some Lots
```
Now `x` has the attributes I would like. Is there a `to_*` function to convert it to `c(0.0, 0.5, 1, 1.5)`? `to_value(x)` gives me the indices instead and changes the labels: 
```
to_value(x)
# [1] 1 2 3 4
# attr(,"labels")
#   None Little   Some   Lots 
#      1      2      3      4 
```

This might be a bit outside the intended use of the package but I do think it would be a useful set of features, I often want to associate numeric values to factor levels different from the factor indices, and I don't know of another package that does something like this.

Thanks.

**Comment by strengejacke** [comment]
The labelled data functions have been moved to the [sjlabelled-pkg](https://github.com/strengejacke/sjlabelled). `as_numeric()` is the equivalent of `to_value()` there. You can use `as_numeric(..., use.labels = TRUE)` (see Examples).
