### ISSUE TITLE
Bug: saving dataframes concatenates categories with identical labels

### ISSUE THREAD

**Issue by methodds** [strengejacke/sjmisc#63]
Hi,

when saving a dataframe with ``write_stata()`` that has identical value labels for some categories, these categories get concatenated (and other categories seem to get messed up as well):

```
library(sjmisc)
 d <- read_stata('ZA5250_v2-0-0_nomv.dta') 

> frq(d$mm01)
# ISLAMAUSUEBUNG IN BRD BESCHRAENKEN

 val               label frq raw.prc valid.prc cum.prc
 -10         TNZ: FILTER   0    0.00      0.00    0.00
  -9        KEINE ANGABE   0    0.00      0.00    0.00
   1 STIMME GAR NICHT ZU 799   22.89     23.79   23.79
   2                  .. 353   10.11     10.51   34.30
   3                  .. 233    6.68      6.94   41.23
   4                  .. 492   14.10     14.65   55.88
   5                  .. 421   12.06     12.53   68.41
   6                  .. 341    9.77     10.15   78.57
   7   STIMME VOELLIG ZU 720   20.63     21.43  100.00
  NA                  NA 131    3.75        NA      NA


> 
> write_stata(d, 'ZA5250_v2-0-0_nomv_2.dta')
> 
> d2 <- read_stata('ZA5250_v2-0-0_nomv_2.dta')
  |=====================================================================================| 100%
> frq(d2$mm01)
# ISLAMAUSUEBUNG IN BRD BESCHRAENKEN

 val               label  frq raw.prc valid.prc cum.prc
   1 STIMME GAR NICHT ZU  799   22.89     22.89   22.89
   2         TNZ: FILTER   79    2.26      2.26   25.16
   3                  .. 1840   52.72     52.72   77.88
   4   STIMME VOELLIG ZU  720   20.63     20.63   98.51
   5        KEINE ANGABE   52    1.49      1.49  100.00
  NA                  NA    0    0.00        NA      NA
```

I'm not 100% sure whether this is the same problem, but this concatenation effect also appears for some plots (even before saving the dataframe and reloading it):

```
library(sjPlot)
sjp.xtab(d$mm01, d$sex,bar.pos  = 'dodge',
         margin = 'cell', show.total = F)
```
![image](https://cloud.githubusercontent.com/assets/7460499/26576861/b2ad5632-452a-11e7-87f0-fcc354f03a5a.png)

The dataset for reproduction is available [here](https://www.dropbox.com/s/pa614q3li0c4i2w/ZA5250_v2-0-0_nomv.dta?dl=1).

On a sidenote, I think it's a horrible idea to have identical value labels in the first place, but unfortunately that is common practice for some of the big social science surveys..

**Comment by sjPlot** [comment]
Have you checked the simple `table()`-command? And have you checked the same with the haven package?

**Comment by strengejacke** [comment]
Ok, it's due to `to_label()`, which is used when saving data, or when creating cross tables (cf. also `flat_table()`). I think I'll solve this issue by writing a new function `tidy_labels()`, similair to `?tibble::tidy_names`.

**Comment by strengejacke** [comment]
Ok, can be fixed with `tidy_labels()`, which is a new function of [sjlabelled](https://github.com/strengejacke/sjlabelled). Will commit tonight.

**Comment by methodds** [comment]
Perfect, thank you :) Do you have a rough schedule for when you will schedule the next CRAN releases for sjPlot and sjmisc?

**Comment by methodds** [comment]
Oh and will sjlabelled be loaded automatically in the future when loading sjmisc? Or would a user need an additional library(sjlabelled) for the label functions? From what I can tell, your plan is to move all label functions from sjmisc to sjlabelled right?

**Comment by strengejacke** [comment]
Yes, sjlabelled is now dedicated to work with labelled data, while sjmisc will focus on data / variable transformation. Once dplyr 0.6 is out, sjlabelled, sjmisc and sjstats will be submitted to CRAN (and possibly strengejacke, which will load these pkgs). You don't need to load "sjlabelled", unless you want to use the labelling-functions manually.
