### ISSUE TITLE
Using frq() function inside a function

### ISSUE THREAD

**Issue by cullenjd** [strengejacke/sjmisc#65]
I receive the following error when trying to use the sjmisc::frq() function inside another function:
` Error in eval(x$expr, data, x$env) : object 'var' not found`  

Here's some example code that produces the error:
```
# load library
library(sjmisc)

# create an example df
df <- data.frame(var1 = floor(runif(300, min = 1, max = 6)), id = sample(123456:999999, 300))

# create value labels
five_pt_freq_fmt <- c(`1 - Never` = 1,
                      `2 - Rarely` = 2,
                      `3 - Sometimes` = 3,
                      `4 - Very Often` = 4,
                      `5 - Always` = 5)

# assign value labels to variable
df$var1 <- set_labels(df$var1, labels = five_pt_freq_fmt, force.labels = T)

# frequency table
frq(df, var1)

# function to produce the same frequency table as above
test_fn <- function(df, var) {
        frq(df, var)
}

test_fn(df, "var1") # produces error
```
I'm sure it's an error on my part in how I'm writing my function, but I'm stumped. Any help would be very much appreciated. My complete function is a bit more complex, producing plots for the data for different samples from the whole dataset.

**Comment by strengejacke** [comment]
Ok, I think the problem is that evaluating the `...`-argument from `frq()` inside a function changes the "name" of the variable that is searched for in the data frame. I'm not sure if I find a quick solution, however, you can use following code, which solves your problem:

```
test_fn <- function(df, var) {
  x <- as.character(substitute(var))
  frq(df[[x]])
}

test_fn(df, "var1")
test_fn(df, var1)
```

Is this a feasible solution for you?

**Comment by cullenjd** [comment]
That works great. Thank you very much.
