### ISSUE TITLE
Documentation error: word_wrap()

### ISSUE THREAD

**Issue by michaelwhammer** [strengejacke/sjmisc#68]
Slight error in the documentation for `word_wrap()` - argument is referred to as `codewrap` when the argument is `wrap`

wrap
Maximum amount of chars per line (i.e. line length). If **codewrap** = Inf, no word wrap will be performed (i.e. labels will be returned as is).

**Comment by strengejacke** [comment]
Ok, thanks. Must be a missing slash, I guess I wanted to write `\code{wrap}` to format _wrap_ in monospaced-font.
