### ISSUE TITLE
Dependencies not available

### ISSUE THREAD

**Issue by DeLaRiva** [strengejacke/sjmisc#73]
Hi,
unfortunately it's not possible for me to install the packages sjPlot, sjmisc, sjlabelled etc. due to the following error:

> trying URL 'https://cran.rstudio.com/src/contrib/sjlabelled_1.0.1.tar.gz'
> Warning in install.packages :
>   cannot open URL 'https://cran.rstudio.com/src/contrib/sjlabelled_1.0.1.tar.gz': HTTP status was '404 Not Found'

**Comment by strengejacke** [comment]
which R-version are you using? An update of sjlabelled was just released on CRAN (v1.0.3), which fixed an issue with R version dependency. Now, sjlabelled requires R >= 3.2, and hence all other packages like sjmisc, sjPlot or sjstats should work again for older R versions (down to 3.2).

**Comment by DeLaRiva** [comment]
Hi, thanks for your response! I have:

> > sessionInfo()
> R version 3.4.1 (2017-06-30)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 14.04.5 LTS

**Comment by strengejacke** [comment]
Try to install `sjlabelled` manually first, current version is 1.0.3 - or download the file and install from file.

**Comment by DeLaRiva** [comment]
I've noticed something: On https://cran.rstudio.com/src/contrib/ there is sjlabelled_1.0.2 and sjlabelled_1.0.3. My RStudio wants to download sjlabelled_1.0.1 so this must be the problem..
Thanks anyway!

**Comment by strengejacke** [comment]
[1.0.3](https://cran.r-project.org/package=sjlabelled) is available as source package, which should be possible to install.
