### ISSUE TITLE
not sure about what the sjp.lmer does

### ISSUE THREAD

**Issue by pluvialis** [strengejacke/sjmisc#74]
Dear all

I'd like some clarifications about what sjp.lmer actually does. I think the issue comes mainly from the fact that I'm not comfortable with the terminology used in the help documents, so clarification in trivial language would be much appreciated.

> The default behaviour of sjp.lmer seems to do exactly the same as dotplot(ranef(model,condVar=T)), is that right? Thus, if I get it well, it reports the random departure from the fixed slope, i.e. speaking trivially, the sjp.lmer plot is centered on the fixed effect slope. Is this true?

> Then, what does sjp.lmer(type="rs.ri") show? The actual slopes given random variation, or the individual slopes relative to the fixed slope? 

To clarify my question: if my fixed slope is, say, -4 and I have two individuals with random slope estimates (-1) and (+1), does this plot show lines with slopes (-1) and (+1) or (-5) and (+5)? 

The attached files show outputs of the default sjp.lmer and sjp.lmer(type="rs.ri") for the following model: 

`mod<-lmer(Nestweight~Nest+Year.cat+(Nest|Ring.cat),data=dat)`

[Rplot_2.pdf](https://github.com/strengejacke/sjmisc/files/1348115/Rplot_2.pdf)

In relation to my questions how should this plot be interpreted? Are these the actual, Ring.cat - level slopes of the Nest effect against the response variable, or the Ring.cat slopes conditional to the value of the fixed effect slope? 

Thanks all for answers. 

JY Barnagaud

**Comment by strengejacke** [comment]
The `"rs.ri"`-option simply displays the random slopes, starting at the global (fixed) intercept for all slopes, and each random slope has its random intercept as offset from the global intercept. So, it's simply:

y = global.intercept + random.intercept(j) + random.slope(j)

I did this plot-type primarily to inspect trends over time for different subjects (growth models) in an easy way.


And 2nd:

> The default behaviour of sjp.lmer seems to do exactly the same as dotplot(ranef(model,condVar=T)), is that right? 

Yes, that's right.

> speaking trivially, the sjp.lmer plot is centered on the fixed effect slope. Is this true?

slope or intercept, depending on whether your model has a random intercept and/or slope.

**Comment by strengejacke** [comment]
Regarding to your second questions, these are the random slopes, with the random intercept as start offset for the x-axis.
