### ISSUE TITLE
frq() in knitr

### ISSUE THREAD

**Issue by jemus42** [strengejacke/sjmisc#80]
I just found out that `sjPlot::sjt.frq` is going to be deprecated, so I tried switiching to `sjmisc::frq` in a `bookdown` document. However, I couldn't figure out how to properly use the function in RMarkdown, as all the output options (`out = `) cause a browser window to open with the table output, while no output is rendered in the actual document.

Ever since the `sjt.*` functions started working well within RMarkdown I assumed that's going to be a solved problem, but now I'm mildly concerned we're going to have to resort to weird hacks again (like assigning the output to an object and then printing that in some way in an inline-chunk, like before).

Any clarification on that would be appreciated,  
thanks.

**Comment by strengejacke** [comment]
I had to revise the knitr-print-methods in sjPlot to make functions like `frq()`, `mwu()` or `descr()` work in markdown documents. If you install the current dev-version of sjPlot, everything should work when you use `frq(..., out = "v")` in knitr-docs . Can you confirm this?

**Comment by jemus42** [comment]
Yes, it works with the dev version, thank you!

As a side note, there might still be some issues with HTML character escapes, see

![](https://dump.jemu.name/2018-04-7kdtpe6cpjivdmb.png)

- `<integer&gt` in the header
- `x&#772=` in the footer

**Comment by jschrewe** [comment]
I'm trying to generate a basic overview for a pretty large dataset (with more then 50 columns to evaluate). I'm not entirely sure if I use knit correctly, but after trying

```
{r, results='asis'}
start <- 47
end <- 50

for(i in start:end) {
  x <- frq(df[[i]], out="v")
}
```

nothing happened and trying 

```
{r, results='asis'}
start <- 47
end <- 50

for(i in start:end) {
  x <- frq(df[[i]], out="v")
  print(x)
}
```

opened a browser window for every table. 

Is this even possible to include the results of `frq` in a markdown document like this?

**Comment by iago-pssjd** [comment]
Currently, at lest for me in Debian 9, R 3.6.3 and with last version of `sjmisc`, an R chunk in an Rmd document with `output: word_document` and with `echo=FALSE` like

```
pcpc_data %>%
  frq(int, out = "v")
```
 or instead
```
pcpc_data %>%
  frq(int) %>%
   tab_df()
```
appear fully misconfigured, with each string in a separate line.
