### ISSUE TITLE
set_na() problem with "NA"

### ISSUE THREAD

**Issue by frankcsliu** [strengejacke/sjmisc#81]
load("tscs2013q2.rda")  # http://jmp.sh/pJGXkxa
library(sjmisc)
tscs2013 <- set_na(tscs2013, na=c(93:99, "NA"))

The "NA"s cannot be removed via this comand at all.  
Could you check that this function could deal with strings like "NA"  in a data set? 
It used to work well.  

Thanks!

**Comment by strengejacke** [comment]
As far as I can see (using `lapply()` to look for values from 93 to 99 and for "NA"), there are no such values in the dataset. So there are no values that could be replaced resp. set to NA.

**Comment by strengejacke** [comment]
```r
x <- data.frame(a = c("NA", "a", "b"), b = c(1,2,99))
x

#>    a  b
#> 1 NA  1
#> 2  a  2
#> 3  b 99

set_na(x, na = c(99, "NA"))

#> # A tibble: 3 x 2
#>    a        b
#> 1 NA        1.
#> 2  a        2.
#> 3  b       NA 
```

I don't see any issues here, in the first data frame, `a` is a character vector and the value "NA" is a character, in the 2nd data frame, correct values are set to `NA.
