### ISSUE TITLE
sjmisc::remove_labels deprecated?

### ISSUE THREAD

**Issue by IndrajeetPatil** [strengejacke/sjmisc#82]
I am currently using `sjmisc` and I was reading your blog post about how to use it. In particular, I wanted to use the function `sjmisc::remove_labels`, which is described here. But this function is no longer in the namespace of `sjmisc`. Has it been deprecated? 

![image](https://user-images.githubusercontent.com/11330453/39342923-34f57a52-49a8-11e8-9191-4abd42a707a1.png)

I also went through `NEWS.md` for the package on CRAN (https://cran.r-project.org/web/packages/sjmisc/news.html), but couldn't find any information about this.

**Comment by strengejacke** [comment]
See news for release v2.6.0. the labelled functions are now in package _sjlabelled_.
