### ISSUE TITLE
Functionality with class "averaging"

### ISSUE THREAD

**Issue by wraymond** [strengejacke/sjmisc#83]
I love this package but have not had any luck with it working with model objects fit with the `model.avg` function in the `MuMIn` package. `model.avg` creates an object of class averaging which throws and error in `sjt.glm()`. I have a case where I would like to report the coefficients of multiple models fir in slightly different ways.  If possible it would be great to add this functionality in the next version.

**Comment by strengejacke** [comment]
It's an sjPlot-issue, I moved your issue over there...
