### ISSUE TITLE
sjmisc::to_factor() not working

### ISSUE THREAD

**Issue by frankcsliu** [strengejacke/sjmisc#84]
The function seems not working. I double-checked that the argument does not help change the base via ref.lvl argument, either using label or number. 

Please help check this. Thanks!

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by strengejacke** [comment]
The variable `kao06$pID` is already a factor and thus not processed by `to_factor()`. For factors, you can / must directly use `ref_lvl()`, e.g. `ref_lvl(kao06$pID, lvl = 2)`.
