### ISSUE TITLE
Please check: The T and F setting for the argument na.rm in row_sums() seems reversed

### ISSUE THREAD

**Issue by frankcsliu** [strengejacke/sjmisc#93]
```r
tmp <- cbind(tv,radio,internet,newspaper)
kao06$mediaAtt <- apply(tmp,1,sum)  
table(kao06$mediaAtt) #0~22

# gives the correct result:  
> table(kao06$mediaAtt) #0~22
  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15 
 84  85 167 157 172 121 114  66  58  46  47  13  18  10  12  10 
 16  17  19  20  22 
  5   3   3   2   1 

# if I use sjmisc::row_sums()
library(sjmisc)
kao06 <- row_sums(kao06, tv, radio, internet, newspaper, 
                  **na.rm = T**, append = T)
table(kao06$rowsums)

# this gives the wrong one:
> table(kao06$rowsums)
  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15 
 98  95 179 162 178 126 125  68  59  46  48  13  18  10  12  10 
 16  17  18  19  20  22 
  5   3   1   3   2   1 

# if set the argument to F, then it became right: 
kao06 <- row_sums(kao06, tv, radio, internet, newspaper, 
                  **na.rm = F**, append = T)
table(kao06$rowsums)

> table(kao06$rowsums)
  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15 
 84  85 167 157 172 121 114  66  58  46  47  13  18  10  12  10 
 16  17  19  20  22 
  5   3   3   2   1 
```

**Comment by strengejacke** [comment]
Could you compare to `rowSums()`? Internally, `row_sums()` just calls `rowSums()`.

**Comment by frankcsliu** [comment]
I checked out ?rowSums and [this discussion](https://stackoverflow.com/questions/33672059/rowsums-with-all-na). I realized that the argument na.rm=T means "ignoring any NA in the cell and continuing to calculate". This is quite opposite to what my understanding that "not including those rows with NA in it.  The original manual was very unclear and could be misleading from today's perspective. I confirm that it is not due to  sjmisc::row_sums. I hope the manual in sjmisc could be more clear, or at least setting the argument na.rm=F as default, just like what rowSums() does. 

Current description of the argument is "TRUE if missing values should be omitted from the calculations."
I strongly suggest that this should be "FALSE if rows with missing values should be omitted from the calculations" followed by setting na.rm=F as default. 

Thanks.

**Comment by frankcsliu** [comment]
for users of sjmisc I will say it is better to adjust the behavior (setting the default value to F and saying that this is the way to get NA for raw sums with n missing values), an easier way. Ultimately, please help pass this message to R core team issuing this misleading/confusing issue. Thanks.
