### ISSUE TITLE
sjt.frq missing?

### ISSUE THREAD

**Issue by b1azk0** [strengejacke/sjmisc#96]
I just noticed that my script (written couple months ago) no longer understands `sjt.frq()` calls and expects to replace them with `frq()`.
Is there any way I can get a nice html table as the old `sjt.frq()` used to do, with current versions of `sjmisc`?

**Comment by strengejacke** [comment]
Yes, simply use `frq(..., out = "viewer")` or (`"browser"`). However, saving to files does not work. This is just recently fixed in a commit, so you need to install sjPlot and sjmisc from GitHub, if you want HTML-output from `frq()` directly saved as file...

**Comment by b1azk0** [comment]
Got it! Thanks a lot.
I wasn't aware that so many changes where made in the meantime :)
