### ISSUE TITLE
rec into the same variable

### ISSUE THREAD

**Issue by andresimi** [strengejacke/sjmisc#97]
Hi, the standard option in rec is recoding into a new variable. Is there a way for doing this into the same variable? When I use suffix="" it creates new variables with numbers as suffix.

**Comment by strengejacke** [comment]
Yes, "overwriting" existing variables is not directly possible (for safety reasons). The current way to do this is to return only the recoded variables (w/o suffix) and replace old variable, using `add_colums()`:

```r
dat <- data.frame(
  a = c(1, 1, 1, 2, 2, 2),
  b = c(1, 1, 1, 3, 3, 3),
  c = c(1, 1, 1, 4, 4, 4)
)

dat %>%
  rec(a, b, rec = "1=5;else=copy", append = F, suffix = "") %>% 
  add_columns(dat)
```
