### ISSUE TITLE
complete_cases returns integer(0) if all cases and no cases are complete

### ISSUE THREAD

**Issue by haugstve** [strengejacke/sjmisc#99]
A minimal example:

A single NA value: All other indexes are returned, this is expected.
`df1 <- tibble(a = rnorm(10), b = c(rnorm(5), NA, rnorm(4)), c = rnorm(10))`
`df1 %>% complete_cases()`
`[1]  1  2  3  4  5  7  8  9 10`

Only NA values: Numeric(0) is returned, this is expected.
`df2 <- tibble(a = rep(NA,10), b = rep(NA,10), c = rep(NA,10))`
`df2 %>% complete_cases()`
`integer(0)`

**No NA values: Numeric(0) is returned, all indexes where expected.**
`df3 <- tibble(a = rnorm(10), b = rnorm(10), c = rnorm(10))`
`df3 %>% complete_cases()`
`integer(0)`

**Comment by strengejacke** [comment]
Fixed, will commit tonight.
